### ISSUE TITLE
Secret key is not available as $config->secretkey if only set in config.php with $CFG->local_envbar_secretkey

### ISSUE THREAD

**Issue by abias** [catalyst/moodle-local_envbar#103]
Due to the way how the plugin's settings are built, the secret key is not available as $config->secretkey if only set in config.php with $CFG->local_envbar_secretkey

Steps to reproduce:
* Set $CFG->local_envbar_secretkey='foo' in config.php
* Install the plugin
* Go to /local/envbar/index.php

Result:
* You will see that there is the "SomeRandomAlphanumericalString" placeholder and not "foo" in the secret key box
* As the code for the scheduled task only works with $config->secretkey, the task will not work correctly

Workaround:
* As admin, don't use $CFG->local_envbar_secretkey and set the secret key on /local/envbar/index.php

**Comment by dmitriim** [comment]
fixed in #111
