### ISSUE TITLE
Add switch to enable / disable debugging

### ISSUE THREAD

**Issue by abias** [catalyst/moodle-local_envbar#115]
We have been using local_envbar for a while now with our test / dev systems and have a feature request which we would like you to consider:

By design, test / dev systems often have debugging enabled to support testing / development tasks. On the other hand, having debugging enabled might slow down the work significantly or might disturb end users who are sent to a test system for acceptance tests. Changing the debug mode in the Moodle UI or in config.php every now and then can be quite cumbersome. This is where local_envbar could be helpful as it shows a omnipresent information / toolbar in each test / dev system.

I would propose these enhancements:
* Add a setting to /admin/category.php?category=envbar which allows you to add "debugging switch" to the envbar.
* Add settings to /admin/category.php?category=envbar which lets you define
1. The debugging level for "Debugging Off" + if debugging should be output to the browser
2. The debugging level for "Debugging On" + if debugging should be output to the browser
* If these settings are enabled / configured, the envbar will show a switch which informs every user about the current debugging status (On or Off)
* If these settings are enabled / configured, the envbar will show a switch which lets only admins change the current debugging status (On to Off and vice-versa) and which will reload the page afterwards
* Add a note to the readme or the settings description that this feature will only work if debugging levels and visibility settings aren't hardcoded in config.php

**Comment by dmitriim** [comment]
HI Alex,

In other words, you want to have an indicator which will show a status of the debugging mode as well as a switch (for admins) to be able to enable/disable the debugging mode at any page? Also you'd like this feature to be configurable in the plugin settings. I like this idea. :+1: 

_> which will reload the page afterwards_
I would suggest to have an ajax request for that. But not critical. 

_>Add a note to the readme or the settings description that this feature will only work if debugging levels and visibility settings aren't hardcoded in config.php_
Probably would be good to somehow let admins know that the switch is not working for that reason.

Also it makes sense to have two options for admins "Debugging On" and "Debug Display". Or maybe having these two options in one switch. As in most scenarios having just one debugging on doesn't make any sense.   

Please feel free to work on this feature. It will be integrated as per specs provided.

**Comment by abias** [comment]
Hi Dmitrii,

> In other words, you want to have an indicator which will show a status of the debugging mode as well as a switch (for admins) to be able to enable/disable the debugging mode at any page? Also you'd like this feature to be configurable in the plugin settings. 

I think this summary is spot-on.

> I like this idea.

Great!

> I would suggest to have an ajax request for that. But not critical.

This depends on how you want to switch to behave. I think there are two options:
1. Having the switch reload the page means that, after I click the switch, the debugging mode will be changed and I will see the same page with / without debugging output again. This will support use cases like "Are there debug problems on this page" and "Hide the debug messages on this page for now". But there are pages in Moodle which can't be reloaded with exactly the same output, so reloading might be a problem.
2. Having the switch send an Ajax request means that, after I click the switch, the page does not change in any way and I won't see any debugging / have any debugging removed until I browser to the next page (with a full page reload). This will support all use cases where I don't care about the debug output on the current page, but want to continue with / without debugging from now on.

Looking at these options, I think I would agree with you that option 2 makes more sense.

> Probably would be good to somehow let admins know that the switch is not working for that reason.

Yeah, you might want to include a small check and a warning message into the settings page where the switch is enabled by admins.
And you might want to disable the switching functionality in the envbar.
But both would be optional to me for now.

> Also it makes sense to have two options for admins "Debugging On" and "Debug Display". Or maybe having these two options in one switch. As in most scenarios having just one debugging on doesn't make any sense.

My usage scenario would be to be able between two status:
1. Debugging set to DEVELOPER + Debug messages are output to the browser
2. Debugging set to NORMAL + Debug messages are not output to the browser 
That's why I proposed to combine the debug level and the debug message showing into one setting (or, respectively, two settings which define together one status of the switch).

Is this what you meant, too, or are you proposing something different?

**Comment by dmitriim** [comment]
Looks like we are on the same page! Cheers

**Comment by dmitriim** [comment]
This feature has been implemented as part of https://github.com/catalyst/moodle-local_envbar/pull/119
