### ISSUE TITLE
Failing unit tests on totara 13 

### ISSUE THREAD

**Issue by yao9394** [catalyst/moodle-local_envbar#149]
Was trying to install this plugin for a totara 13. I had two failing unit test

1) local_envbar_lib_test::test_clean_envbars
Failed asserting that two strings are equal.
--- Expected
+++ Actual

and 

2) local_envbar_lib_test::test_set_debug_config
Failed asserting that '32767' matches expected 0.

/var/www/server/local/envbar/tests/lib_test.php:304
/var/www/server/lib/phpunit/classes/base_testcase.php:665
/var/www/server/lib/phpunit/classes/advanced_testcase.php:68

To re-run:
 test/phpunit/vendor/phpunit/phpunit/phpunit -c /var/www/test/phpunit/phpunit.xml server/local/envbar/tests/lib_test.php

a bit more info, when I put `var_dump(get_config('core', 'additionalhtmltopofbody'));` one line above and under this line
https://github.com/catalyst/moodle-local_envbar/blob/master/classes/local/envbarlib.php#L360

On totara 13, the value of get_config('core', 'additionalhtmltopofbody') seems changed by `$CFG->additionalhtmltopofbody .= $html;` but on a moodle, it does not. Not sure about if this is a totara thing/error, this is for the first failing test, the second seems to be failing for similar cause.  
``

**Comment by ScottVerbeek** [comment]
Fixed in https://github.com/catalyst/moodle-local_envbar/pull/154
