### ISSUE TITLE
At small screen sizes with large message should do an ellipsis instead of wrap

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-local_envbar#25]

**Comment by meepster-nz** [comment]
An excellent idea.

**Comment by keevan** [comment]
Question, how did you want the action links to appear, as the elements themselves are in an inline state at the moment:

With it as ellipsis
![image](https://user-images.githubusercontent.com/9924643/120974281-4d024580-c7b3-11eb-9c71-1eeca3945667.png)

Without an eillipsis:
![image](https://user-images.githubusercontent.com/9924643/120974439-7de27a80-c7b3-11eb-8b4e-805a1d9c84ab.png)

**Comment by keevan** [comment]
I've added a PR #176  which should result in the following layout:
![image](https://user-images.githubusercontent.com/9924643/120976776-0235fd00-c7b6-11eb-81b2-d3e1a56aac3a.png)
