### ISSUE TITLE
SCRIPT_FILENAME does not match symlinked $CFG->dirroot

### ISSUE THREAD

**Issue by nhoobin** [catalyst/moodle-local_envbar#37]
To prevent duplication of the envbar we have a check 

> if ($_SERVER['SCRIPT_FILENAME'] === $CFG->dirroot.'/admin/settings.php')

The script filename will not match the string we are comparing against.

> link: /var/www/sites/moodle/current
> target: /var/www/sites/moodle/releases/release_52

The duplication can also happen when viewing /admin/search.php so we will add another check for that file.

**Comment by brendanheywood** [comment]
If we wanted to be super anal don't use /admin, use $CFG->admin (see config-dist.php line 116 for why) or instead use moodle_url() which handles this for you

Also run everything through realpath() first to fix the other issue

http://php.net/manual/en/function.realpath.php
