### ISSUE TITLE
Add support for multilang tags in "text to show"

### ISSUE THREAD

**Issue by abias** [catalyst/moodle-local_envbar#71]
Hi,

I'm looking forward to bring your very helpful plugin into production. 
However, there are some things would would be even more helpful if they would exist:

Could you please think about adding support for multilang tags in the "text to show" setting, i.e. process it with format_string() ?

Background information: I want not only to show the name of the Moodle instance, but also a quick & helping description in the user's language about the instance.

Thanks,
Alex

**Comment by brendanheywood** [comment]
thanks @abias for your various feedback. You look like you a moodle dev and most of these issues seem rather small - so if you are keen to implement them we are always open to pull requests. Almost all of our dev is sponsored by clients who need things so if it's not on their radar then it can sometime be a while before new features like this get done. thanks again!

**Comment by abias** [comment]
Sure, I can try to create a pull request for the stuff I had reported. I just wanted to announce the need first because not every plugin maintainer wants to accept code contributions.

To be able to contribute code, could you please give me a quick overview about the status of the master branch and the plugin as a whole?
I see that it is several commits ahead of the version published in the Moodle plugin repo, but it this a stable and running version I can build on or is it WIP? Additionally, there are several issues open like #60 which have commits in master branch but are not closed yet?

**Comment by brendanheywood** [comment]
Yeah sure, generally we try to keep things on a single branch until we are forced to have separate stable branches. So in theory for this plugin master is always stable and always supports everything, ie the pull request should bump the version too. The commits out of sync is just laziness, I wish there was some post pull request hooks we could implement to push it into the plugin directory so this is always current.
