### ISSUE TITLE
It may cause behat tests to fail.

### ISSUE THREAD

**Issue by roperto** [catalyst/moodle-local_envbar#80]
In tests where the administrator logs out, the envbar is displayed on top of the user menu dropdown therefore it fails as cannot log out (cannot click element).

For now I am completely disabling envbar in behat tests as it is not used there.

If we decide to implement behat tests in envbar we'll need to rethink this solution.

**Comment by brendanheywood** [comment]
This is a real bug, if behat can't logout then a real admin can't logout either. The problem here is probably the css applied which depends on the theme.
